# Generated by Django 5.0.6 on 2024-08-19 00:29

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='adft6543kb', length=10, max_length=20, null=True, prefix=''),
        ),
    ]
