# Generated by Django 5.0.6 on 2024-08-19 01:14

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='adft6543kb', length=25, max_length=40, null=True, prefix=''),
        ),
    ]
