# Generated by Django 4.2.15 on 2024-08-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0015_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
