# Generated by Django 5.0.6 on 2024-08-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='log_image')),
                ('price', models.CharField(max_length=300)),
                ('qty', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
