# Generated by Django 5.0.6 on 2024-08-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(null=True)),
                ('which_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.logs')),
            ],
        ),
    ]
