# Generated by Django 5.0.6 on 2024-08-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_logdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logdetails',
            options={'verbose_name_plural': 'LogDetails'},
        ),
        migrations.RemoveField(
            model_name='logs',
            name='qty',
        ),
        migrations.AddField(
            model_name='logs',
            name='category',
            field=models.CharField(choices=[('facebook_50', 'Facebook (Below 50 Friends)'), ('facebook_other', 'Facebook (Other Countries)'), ('facebook_dating', 'Facebook Dating'), ('facebook_usa', 'Facebook USA'), ('instagram', 'Instagram'), ('texting_numbers', 'Texting Numbers'), ('tools', 'Tools'), ('twitter', 'Twitter'), ('vpn', 'VPN'), ('reddit', 'Reddit'), ('tiktok', 'Tiktok'), ('mails', 'Mails')], max_length=200, null=True),
        ),
    ]
