# Generated by Django 5.0.6 on 2024-08-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
