# Generated by Django 5.0.6 on 2024-08-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_logs_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='in_stock',
        ),
    ]
