# Generated by Django 5.0.6 on 2024-08-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdetails',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
