# Generated by Django 5.0.6 on 2024-08-17 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_logdetails_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.logdetails'),
        ),
    ]
