# Generated by Django 5.0.6 on 2024-08-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cart_log_alter_order_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
