# Generated by Django 5.0.6 on 2024-08-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='info',
            field=models.CharField(blank=True, max_length=1000000000000000000000000000000000000000000000000, null=True),
        ),
    ]
