# Generated by Django 5.0.6 on 2024-08-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
