# Generated by Django 5.0.6 on 2024-08-18 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_viewlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewlog',
            name='log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order'),
        ),
    ]
