# Generated by Django 4.2.15 on 2024-08-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_cart_log_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.CharField(default='1', max_length=300, null='True'),
            preserve_default='True',
        ),
    ]
