# Generated by Django 4.2.15 on 2024-08-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_order_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='log',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
