# Generated by Django 4.2.15 on 2024-08-30 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_order_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdetails',
            name='which_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logcount', to='core.logs'),
        ),
    ]
