# Generated by Django 4.2.15 on 2024-08-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_logdetails_which_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='email',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='email',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
