# Generated by Django 4.2.15 on 2024-08-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_order_email_transaction_history_email_wallet_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
