# Generated by Django 4.2.15 on 2024-09-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_logs_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='logs',
            name='category',
            field=models.CharField(blank=True, choices=[('facebook_50', 'Facebook (Below 50 Friends)'), ('facebook_other', 'Facebook (Other Countries)'), ('facebook_dating', 'Facebook Dating'), ('facebook_usa', 'Facebook USA'), ('instagram', 'Instagram'), ('texting_numbers', 'Texting Numbers'), ('tools', 'Tools'), ('twitter', 'Twitter'), ('vpn', 'VPN'), ('reddit', 'Reddit'), ('tiktok', 'Tiktok'), ('mails', 'Mails')], max_length=200, null=True),
        ),
    ]
