# Generated by Django 4.2.15 on 2024-09-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_category_options_alter_logs_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thelogs', to='core.category'),
        ),
    ]
