# Generated by Django 4.2.15 on 2024-09-07 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_logs_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thelogs', to='core.category'),
        ),
    ]
