# Generated by Django 4.2.15 on 2024-09-09 00:46

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_logs_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgaccs', length=10, max_length=20, null=True, prefix='cat'),
        ),
    ]
