# Generated by Django 4.2.15 on 2024-09-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_category_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
