# Generated by Django 4.2.15 on 2024-09-15 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_logorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logorder',
            options={'verbose_name_plural': 'Log Order'},
        ),
    ]
