# Generated by Django 4.2.15 on 2024-09-15 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_logorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logorder', to='core.order'),
        ),
    ]
