# Generated by Django 4.2.15 on 2024-11-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_logorder_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopviaclone22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(null=True)),
                ('password', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Shopviaclone22',
            },
        ),
    ]
