# Generated by Django 4.2.15 on 2024-11-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_logs_from_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='from_api',
            field=models.BooleanField(default=False),
        ),
    ]
