# Generated by Django 4.2.15 on 2024-11-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_category_from_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='DollarRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(help_text='Please do not add another dollar rate. Keep Changing this one', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Dollar Rate',
            },
        ),
    ]
