# Generated by Django 4.2.15 on 2024-11-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_dollarrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='image',
            field=models.ImageField(blank=True, upload_to='log_image'),
        ),
    ]
