# Generated by Django 4.2.15 on 2024-11-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_logs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='image',
            field=models.ImageField(blank=True, default='fb.jpeg', upload_to='log_image'),
        ),
    ]
