# Generated by Django 4.2.15 on 2024-11-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_logs_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
