# Generated by Django 4.2.15 on 2024-11-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_logs_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='hbscountry',
            field=models.CharField(blank=True, default='us', max_length=100),
        ),
    ]
