# Generated by Django 4.2.15 on 2024-11-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_logs_hbscountry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='hbscountry',
        ),
    ]
