# Generated by Django 4.2.15 on 2024-11-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_logs_hbscountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='api_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
