# Generated by Django 4.2.15 on 2024-11-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_logs_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopviaclone22',
            name='balance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopviaclone22',
            name='percentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
