# Generated by Django 4.2.15 on 2024-11-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_shopviaclone22_balance_shopviaclone22_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='to_add',
            field=models.CharField(blank=True, max_length=10000000, null=True),
        ),
    ]
