# Generated by Django 4.2.15 on 2024-11-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_wallet_to_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='to_add',
            field=models.CharField(blank=True, default=0, max_length=10000000, null=True),
        ),
    ]
