# Generated by Django 4.2.15 on 2025-01-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accsmtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(null=True)),
                ('password', models.TextField(null=True)),
                ('percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Accsmtp',
            },
        ),
    ]
