# Generated by Django 4.2.15 on 2025-01-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_accsmtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='from_acc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logs',
            name='from_acc',
            field=models.BooleanField(default=False),
        ),
    ]
