# Generated by Django 4.2.15 on 2025-01-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_category_from_acc_logs_from_acc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verify_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Verify Payments',
            },
        ),
    ]
