# Generated by Django 4.2.15 on 2025-07-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(null=True)),
                ('used', models.BooleanField(default=False)),
                ('which_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profilelog', to='core.logs')),
            ],
            options={
                'verbose_name_plural': 'ProfileDetails',
            },
        ),
    ]
