# Generated by Django 5.2.6 on 2025-09-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_bank_account_user_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clonevn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(null=True)),
                ('password', models.TextField(null=True)),
                ('percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clonevn',
            },
        ),
    ]
