# Generated by Django 5.2.6 on 2025-09-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_clonevn'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_id',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
