# Generated by Django 6.0 on 2025-12-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_category_cat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('flag', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='S2_Num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('vendor_price', models.TextField(null=True)),
                ('custom_price', models.TextField(null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('has_premium', models.BooleanField(default=True)),
                ('price_changed', models.BooleanField(default=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'S2 Numbers',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('flag', models.TextField(null=True)),
            ],
        ),
    ]
