# Generated by Django 6.0 on 2025-12-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_country_s2_num_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s2_num',
            name='vendor_price',
        ),
    ]
