# Generated by Django 6.0 on 2025-12-19 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_remove_s2_num_vendor_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_id', models.TextField(null=True)),
                ('service', models.TextField(null=True)),
                ('key', models.TextField(null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('time', models.PositiveIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.TextField(null=True)),
                ('profit', models.TextField(null=True)),
                ('phone_number', models.TextField(null=True)),
                ('delete', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=300, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('vendor', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
