# Generated by Django 6.0 on 2025-12-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_smsorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='vendor',
            field=models.BooleanField(default=False),
        ),
    ]
