# Generated by Django 6.0 on 2026-02-01 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_wallet_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('api_key', models.TextField(null=True)),
                ('api_url', models.TextField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('percentage', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('balance', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'APIs',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('code', models.CharField(max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Platform',
            },
        ),
        migrations.CreateModel(
            name='SMMCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'SMM Categories',
            },
        ),
        migrations.CreateModel(
            name='SMMService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('rate', models.TextField(null=True)),
                ('min', models.TextField(null=True)),
                ('max', models.TextField(null=True)),
                ('from_id', models.CharField(max_length=100, null=True)),
                ('dripfeed', models.CharField(max_length=100, null=True)),
                ('refill', models.CharField(max_length=100, null=True)),
                ('cancel', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.smmcategory')),
            ],
            options={
                'verbose_name_plural': 'SMM Services',
            },
        ),
        migrations.CreateModel(
            name='SMMOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, null=True)),
                ('name', models.TextField(null=True)),
                ('serviceid', models.TextField(null=True)),
                ('link', models.URLField(null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('qty', models.TextField(null=True)),
                ('api_key', models.TextField(null=True)),
                ('api_url', models.TextField(null=True)),
                ('api_name', models.TextField(null=True)),
                ('price', models.TextField(null=True)),
                ('charge', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('start_count', models.CharField(blank=True, max_length=100, null=True)),
                ('remain', models.CharField(blank=True, max_length=100, null=True)),
                ('refunded', models.BooleanField(default=False)),
                ('admin_change', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.smmservice')),
            ],
            options={
                'verbose_name_plural': 'SMM Orders',
            },
        ),
    ]
