from django.urls import path
from backend import views

urlpatterns = [
    # path('s2/', views.s2_get_api, name="s2"),
    path('balance/us/', views.s2_balance, name="s2b"),
    path('balance/all/', views.all_balance, name="all_balance"),
    path('s2-sync/', views.s2_get_api, name="list"),
    path('sync_services/us/', views.s2_provider_sync, name="s2_provider_sync"),
    path('sync-all/', views.all_provider_sync, name="all_provider_sync"),
    path('all_sync/', views.list_all_get_api, name="list_all"),
    
    
    path('', views.index, name="b_index"),
    # path('update/', views.update_api_orders, name="update_api_orders"),
    # path('pro/', views.delete_this, name="delete_this"),
    # History URL
    path('transactions/', views.history, name="history"),
    path('log/new/', views.add_new_log, name="add_new_log"),
    path('log/', views.log, name="log"),
    path('logdetails/', views.logdetails, name="logdetails"),
    path('transactions/delete/<id>', views.history_delete, name="history_delete"),
    path('users/', views.users, name="users"),
    path('users/add_funds/<id>', views.add_funds, name="add_funds"),
    path('users/delete/<id>', views.user_delete, name="user_delete"),
    path('users/bulk_action/delete', views.user_bulk, name="user_bulk"),
    path('users/save/<id>', views.save_funds, name="add_funds"),
    # path('wallet/', views.wallet, name="wallet"),
    # path('edit-wallet/<id>/', views.edit_wallet, name="edit_wallet"),
    # path('manual/', views.manual, name="manual"),
    # path('edit-manual/<id>/', views.edit_manual, name="edit_manual"),
    # path('delete-manual/<id>/', views.delete_manual, name="delete_manual"),
    # path('edit-api/<id>/', views.edit_api, name="edit_api"),
    # path('new-api/', views.new_api, name="new_api"),
    # path('list/<id>/', views.s2_get_api, name="list"),
    # Order URL
    path('order/', views.orders, name="b_orders"),
    path('sms-order/', views.sms_orders, name="smsb_orders"),
    path('order/view/<id>', views.view_orderlog, name="view_order"),
    # path('order/bulk_action/pending', views.order_bulk_pending, name="order_bulk_pending"),
    # path('order/bulk_action/completed', views.order_bulk_completed, name="order_bulk_completed"),
    # path('order/bulk_action/inprogress', views.order_bulk_progress, name="order_bulk_progress"),
    # path('order/bulk_action/delete', views.order_bulk_cancel, name="order_bulk_cancel"),
    # path('order/bulk_action/resend', views.order_bulk_resend, name="order_bulk_resend"),
    # path('order/bulk_action/refund', views.order_bulk_refund, name="order_bulk_refund"),
    # path('order/delete/<id>', views.service_delete, name="service_delete"),
    
    
    path('statistics/', views.statistics, name="bstatistics"),
    # path('delete/', views.delete_test, name="delete_test"),
    # Category URL
    path('category/', views.category, name="category"),
    path('category/update/<id>/', views.category_edit, name="category_edit"),
    path('category/create/', views.category_create, name="category_create"),
    path('category/new', views.category_new, name="category_new"),
    path('category/edit/<id>', views.category_update, name="category_update"),
    path('category/delete/<id>', views.category_delete, name="category_delete"),
    path('logdetails/update/<id>/', views.logdetails_edit, name="logdetails_edit"),
    path('logdetails/edit/<id>/', views.logdetails_update, name="logdetails_update"),
    path('logdetails/delete/<id>/', views.logdetails_delete, name="logdetails_delete"),
    
    path('log/update/<id>/', views.log_edit, name="log_edit"),
    path('log/edit/<id>/', views.log_update, name="log_update"),
    path('log/delete/<id>/', views.log_delete, name="log_delete"),
    
    path('provider/', views.provider, name="provider"),
    path('bulk/', views.bulk, name="bulk"),
    path('bulk-profile/', views.bulk_profile, name="bulk_profile"),
    path('provider/balance/<id>', views.api_balance, name="api_balance"),
    path('provider/api-list/', views.api_account_list, name="api-account-list"),
    path('provider/update/', views.provider_edit, name="provider_edit"),
    path('provider/update/accs/', views.accsprovider_edit, name="accsprovider_edit"),
    # path('provider/delete/<id>', views.provider_delete, name="provider_delete"),
    # path('provider/new', views.provider_new, name="provider_new"),
    # path('provider/create/', views.provider_create, name="provider_create"),
    path('provider/store/', views.provider_update, name="provider_update"),
    path('provider/store/accs/', views.accsprovider_update, name="accsprovider_update"),
    # path('provider/services/<id>', views.provider_service, name="provider_service"),
    # path('provider/sync_services/<id>', views.provider_sync, name="provider_sync"),
    # path('provider/change_status/<id>', views.provide_change_status, name="provide_change_status"),
    
    # path('provider/all/balance/<id>', views.all_balance, name="all_api_balance"),
    # path('provider/all/update/<id>', views.all_provider_edit, name="all_provider_edit"),
    # path('provider/all/delete/<id>', views.all_provider_delete, name="all_provider_delete"),
    # path('provider/all/new', views.all_provider_new, name="all_provider_new"),
    # path('provider/all/create/', views.all_provider_create, name="all_provider_create"),
    # path('provider/all/store/<id>', views.all_provider_update, name="all_provider_update"),
    # path('provider/all/services/<id>', views.all_provider_service, name="all_provider_service"),
    # path('provider/all/sync_services/<id>', views.all_provider_sync, name="all_provider_sync"),
    # path('provider/all/change_status/<id>', views.all_provider_change_status, name="all_provide_change_status"),
    # path('list/all/<id>/', views.list_all_get_api, name="list_all"),

    # # path('services/', views.services, name="services"),
    # path('provider/import_bulk_services/<id>', views.bulk, name="bulk"),
    path('payments/', views.payment, name="payment"),
    # path('payments/update/<id>', views.payment_edit, name="payment_edit"),
    # path('payments/save/<id>', views.payment_update, name="payment_update"),
    # path('settings/currency/', views.currency, name="currency"),
    # path('settings/email_setting/', views.setting, name="currency"),
    # path('settings/', views.setting, name="settings"),
    # path('settings/email_template/', views.setting, name="currency"),
    # path('settings/website_setting/', views.setting, name="website_setting"),
    # path('settings/payment/', views.settings_payment, name="settings_payment"),
    # path('settings/other/', views.other, name="other"),
    # path('settings/terms_policy/', views.terms, name="terms"),
    # path('settings/cookie_policy/', views.cookie, name="cookie"),
    # path('settings/template/', views.template, name="template"),
    # path('settings/default/', views.default, name="default"),
    # path('settings/website_logo/', views.website_logo, name="website_logo"),
    
    path('clone-shop-provider/balance/<id>', views.clone_shop_api_balance, name="clone-shop-api_balance"),
    path('clone-shop-provider/api-list/', views.clone_shop_api_account_list, name="clone-shop-api-account-list"),
    path('clone-shop-provider/update/', views.clone_shop_provider_edit, name="clone-shop-provider_edit"),
    path('clone-shop-provider/store/', views.clone_shop_provider_update, name="clone-shop-provider_update"),
    
    
    path('logout/', views.lout, name="blogout"),
]