# Generated by Django 6.0 on 2025-12-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('api_url', models.URLField(null=True)),
                ('balance_api_url', models.URLField(null=True)),
                ('order_api_url', models.URLField(null=True)),
                ('service_api_url', models.URLField(blank=True, null=True)),
                ('code_api_url', models.URLField(blank=True, null=True)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('percentage', models.TextField(default='20', null=True)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('balance', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'All Country Providers',
            },
        ),
        migrations.CreateModel(
            name='S2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('api_url', models.URLField(null=True)),
                ('balance_api_url', models.URLField(null=True)),
                ('order_api_url', models.URLField(null=True)),
                ('code_api_url', models.URLField(blank=True, null=True)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('percentage', models.TextField(default='20', null=True)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('balance', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'USA Providers',
            },
        ),
    ]
